<?php

namespace OcraServiceManagerProxy\Proxy\__CG__\EcampCore\Repository;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UserRepository extends \EcampCore\Repository\UserRepository implements \Doctrine\Common\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();


    /**
     * @var object wrapped object to which method calls will be forwarded"
     */
    public $__wrappedObject__;

    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     *
     * @param string $name
     */
    public function __get($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', array($name));

        return $this->__wrappedObject__->$name;
    }

    /**
     *
     * @param string $name
     * @param mixed  $value"
     */
    public function __set($name, $value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', array($name, $value));

        $this->__wrappedObject__->$name = $value;
    }

    /**
     *
     * @param string $name
     */
    public function __isset($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', array($name));

        return isset($this->__wrappedObject__->$name);
    }

    /**
     *
     */
    public function __sleep()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__sleep', array());

        return array('__isInitialized__', '__wrappedObject__');
    }

    /**
     *
     */
    public function __wakeup()
    {
        unset($this->contextProvider, $this->_entityName, $this->_em, $this->_class);
    }

    /**
     *
     */
    public function __clone()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__clone', array());

        $this->__wrappedObject__ = clone $this->__wrappedObject__;
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function findFriends(\EcampCore\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'findFriends', array($user));

        return $this->__wrappedObject__->findFriends($user);
    }

    /**
     * {@inheritDoc}
     */
    public function findFriendInvitations(\EcampCore\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'findFriendInvitations', array($user));

        return $this->__wrappedObject__->findFriendInvitations($user);
    }

    /**
     * {@inheritDoc}
     */
    public function findFriendRequests(\EcampCore\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'findFriendRequests', array($user));

        return $this->__wrappedObject__->findFriendRequests($user);
    }

    /**
     * {@inheritDoc}
     */
    public function createQueryBuilder($alias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'createQueryBuilder', array($alias));

        return $this->__wrappedObject__->createQueryBuilder($alias);
    }

    /**
     * {@inheritDoc}
     */
    public function createNamedQuery($queryName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'createNamedQuery', array($queryName));

        return $this->__wrappedObject__->createNamedQuery($queryName);
    }

    /**
     * {@inheritDoc}
     */
    public function createNativeNamedQuery($queryName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'createNativeNamedQuery', array($queryName));

        return $this->__wrappedObject__->createNativeNamedQuery($queryName);
    }

    /**
     * {@inheritDoc}
     */
    public function clear()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clear', array());

        return $this->__wrappedObject__->clear();
    }

    /**
     * {@inheritDoc}
     */
    public function find($id, $lockMode = 0, $lockVersion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'find', array($id, $lockMode, $lockVersion));

        return $this->__wrappedObject__->find($id, $lockMode, $lockVersion);
    }

    /**
     * {@inheritDoc}
     */
    public function findAll()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'findAll', array());

        return $this->__wrappedObject__->findAll();
    }

    /**
     * {@inheritDoc}
     */
    public function findBy(array $criteria, array $orderBy = NULL, $limit = NULL, $offset = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'findBy', array($criteria, $orderBy, $limit, $offset));

        return $this->__wrappedObject__->findBy($criteria, $orderBy, $limit, $offset);
    }

    /**
     * {@inheritDoc}
     */
    public function findOneBy(array $criteria, array $orderBy = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'findOneBy', array($criteria, $orderBy));

        return $this->__wrappedObject__->findOneBy($criteria, $orderBy);
    }

    /**
     * {@inheritDoc}
     */
    public function __call($method, $arguments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__call', array($method, $arguments));

        return $this->__wrappedObject__->__call($method, $arguments);
    }

    /**
     * {@inheritDoc}
     */
    public function getClassName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassName', array());

        return $this->__wrappedObject__->getClassName();
    }

    /**
     * {@inheritDoc}
     */
    public function matching(\Doctrine\Common\Collections\Criteria $criteria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'matching', array($criteria));

        return $this->__wrappedObject__->matching($criteria);
    }

}
